# Generated by Django 4.1.7 on 2023-04-08 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roast', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('purchase_location', models.CharField(max_length=255)),
                ('purchase_date', models.DateField()),
                ('roast_date', models.DateField()),
                ('freeze_date', models.DateField()),
                ('first_unfreeze_date', models.DateField()),
                ('second_unfreeze_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Brew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grind_size', models.IntegerField(max_length=255)),
                ('brew_time', models.DurationField()),
                ('yield_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('beans_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espresso_tracker.bean')),
            ],
        ),
    ]
