# Generated by Django 4.1.7 on 2023-04-09 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espresso_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bean',
            table='espresso.bean',
        ),
        migrations.AlterModelTable(
            name='brew',
            table='espresso.brew',
        ),
    ]
